# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - master

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '12.x'
          - script: |
              npm install
              npm run build
            displayName: 'npm install and build'

  - stage: SlowRing
    dependsOn: Build
    jobs:
      - deployment: SlowRingDeployment
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'slow-ring'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo Deploying to Slow Ring
                - script: echo Add your deployment steps here

  - stage: FastRing
    dependsOn: SlowRing
    jobs:
      - deployment: FastRingDeployment
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'fast-ring'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo Deploying to Fast Ring
                - script: echo Add your deployment steps here

  - stage: ProductionRing
    dependsOn: FastRing
    jobs:
      - deployment: ProductionRingDeployment
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo Deploying to Production
                - script: echo Add your deployment steps here

